<?php
require_once __DIR__ . '/auth_common.php';
include __DIR__ . '/config.php';

header('Content-Type: application/json; charset=utf-8');

function send_json_error($message, $status_code = 500) {
    http_response_code($status_code);
    echo json_encode(['status' => 'error', 'message' => $message]);
    exit;
}

function ensure_system_settings_table($conn) {
    $conn->query("
        CREATE TABLE IF NOT EXISTS system_settings (
            id TINYINT UNSIGNED NOT NULL PRIMARY KEY DEFAULT 1,
            settings_json LONGTEXT NOT NULL,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    ");
}

function default_system_settings() {
    return [
        'clinicName' => 'DermaView',
        'contactInfo' => '',
        'clinicEmail' => '',
        'clinicContactNumber' => '',
        'businessHours' => '',
        'appointmentSlots' => '',
        'sessionTimeout' => '30',
        'defaultTheme' => 'light',
        'maintenanceMode' => 'off',
        'emailSender' => '',
        'emailReplyTo' => '',
        'reportFooter' => 'Generated by DermaView. Results may vary per patient.',
        'uploadSizeLimit' => '10 MB',
        'allowedImageTypes' => 'JPG, PNG, WEBP',
        'imageRetentionPeriod' => '180 days',
        'emailNotifications' => 'enabled',
        'logo' => ''
    ];
}

function read_system_settings($conn, &$exists = null) {
    ensure_system_settings_table($conn);

    $result = $conn->query("SELECT settings_json FROM system_settings WHERE id = 1");
    if (!$result || $result->num_rows === 0) {
        $exists = false;
        return default_system_settings();
    }

    $exists = true;
    $row = $result->fetch_assoc();
    $saved = json_decode($row['settings_json'] ?? '', true);
    if (!is_array($saved)) {
        $saved = [];
    }

    return array_merge(default_system_settings(), $saved);
}

function clean_system_settings($data) {
    $defaults = default_system_settings();
    $clean = [];

    foreach ($defaults as $key => $default) {
        $value = $data[$key] ?? $default;
        $clean[$key] = is_string($value) ? trim($value) : (string) $value;
    }

    if ($clean['clinicName'] === '') {
        $clean['clinicName'] = $defaults['clinicName'];
    }

    if (!in_array($clean['defaultTheme'], ['light', 'clinical', 'dark', 'contrast'], true)) {
        $clean['defaultTheme'] = 'light';
    }

    if (!in_array($clean['maintenanceMode'], ['off', 'on'], true)) {
        $clean['maintenanceMode'] = 'off';
    }

    if (!in_array($clean['emailNotifications'], ['enabled', 'appointments', 'disabled'], true)) {
        $clean['emailNotifications'] = 'enabled';
    }

    if ($clean['logo'] !== '' && !preg_match('/^data:image\/(png|jpe?g|webp);base64,/i', $clean['logo'])) {
        $clean['logo'] = '';
    }

    if (strlen($clean['logo']) > 350000) {
        send_json_error('Logo image is too large. Please choose a smaller image.', 413);
    }

    return $clean;
}

function save_system_settings($conn, $settings) {
    ensure_system_settings_table($conn);

    $json = json_encode($settings, JSON_UNESCAPED_SLASHES);
    $stmt = $conn->prepare("
        INSERT INTO system_settings (id, settings_json)
        VALUES (1, ?)
        ON DUPLICATE KEY UPDATE settings_json = VALUES(settings_json)
    ");
    $stmt->bind_param('s', $json);

    try {
        return $stmt->execute();
    } catch (Throwable $e) {
        return false;
    }
}

$method = $_SERVER['REQUEST_METHOD'] ?? 'GET';

if ($method === 'GET') {
    try {
        $exists = false;
        echo json_encode([
            'status' => 'ok',
            'settings' => read_system_settings($conn, $exists),
            'exists' => $exists
        ]);
    } catch (Throwable $e) {
        send_json_error('Unable to load system settings.');
    }
    exit;
}

if ($method === 'POST') {
    auth_require_super_admin(true);

    try {
        $raw = file_get_contents('php://input');
        $payload = json_decode($raw, true);
        if (!is_array($payload)) {
            send_json_error('Invalid settings payload.', 400);
        }

        $settings = clean_system_settings($payload);
        if (!save_system_settings($conn, $settings)) {
            send_json_error('Unable to save system settings.');
        }

        echo json_encode(['status' => 'ok', 'settings' => $settings]);
    } catch (Throwable $e) {
        send_json_error('Unable to save system settings.');
    }
    exit;
}

http_response_code(405);
echo json_encode(['status' => 'error', 'message' => 'Method not allowed.']);
?>
